### ISSUE TITLE
Text vs Escaped

### ISSUE THREAD

**Issue by msonawane** [delaneyj/gostar#11]
@delaneyj 

which one of above does the html sanitization and escaping ?
if source code loks like both call html.EscapeString. whats the diffrence ? what will be your advice for regular us ?

Also i noticed you moved away from gostar to templ in datastar project. any perticular reason behind that ? 

Thanks

**Comment by delaneyj** [comment]
@msonawane Text is raw text, Escaped is the html.EscapeString as you can see https://github.com/delaneyj/gostar/blob/main/elements/gostar_builder.go#L285-L300

I tend to use `Text` most of time and Escape for user content.  Obviously `Text` will be faster but **caveat emptor**.

For [Datastar](https://data-star.dev) it's mostly static templating and the tooling around Templ has gotten **so** much better.  I still use gostar, but for heavily dynamic content.  For example I have some stuff where UIs are generated from reflecting on SQL queries.  That kind of thing is hard to do with a templating language versus gostar, which is *just* fluent Go functions.  

Both have there place but for most projects Templ is going to be easier to integrate with things like Tailwind.
