### ISSUE TITLE
Examples in README misleading

### ISSUE THREAD

**Issue by szabba** [delaneyj/gostar#2]
When I used gostart today I had to figure out a couple discrepancies between what the README shows and what code the compiler would actually accept.
* The package to import was not `github.com/delaneyj/gostar/elements/html` but `github.com/delaneyj/gostar/elements`.
* The type most of these functions and their methods methods return is not called `ElementBuilder` but `ElementRenderer`.

**Comment by delaneyj** [comment]
Thank you, I'll update

**Comment by gedw99** [comment]
same here. 

Its a deep code gen system.

**Comment by delaneyj** [comment]
I moved things around to around for all of iconify adding Datastar hooks etc, need to update the readme with a correct example

**Comment by paganotoni** [comment]
The first item mentioned here was covered by #6

**Comment by paganotoni** [comment]
#10 updates README to cover the second item.
cc @delaneyj
