### ISSUE TITLE
Model element

### ISSUE THREAD

**Issue by gedw99** [delaneyj/gostar#3]
https://github.com/immersive-web/model-element

Apples Vision Pro and other 3D web. XR systems use this as a formal way to embed 3D content into the DOM...

I figured you might be interested in this.

**Comment by delaneyj** [comment]
Interesting, I accept PRs :)

**Comment by gedw99** [comment]
So I did a bit more looking into this and it's not a standard yet. If may never be, because these things takes ages to happen.  It also have not DOM description lang with it like A-Frame ( Mozilla project ) does.

If you have a design approach for making 3d with gostar, it owed be cool to know.

**Comment by gedw99** [comment]
ok that makes sense.  

AFrame there is a DOM to describe your 3D scene, but you describe it all in code ?

**Comment by delaneyj** [comment]
No, same as aframe, but not making the same engine choices they are

**Comment by gedw99** [comment]
I am using surreal db with the htmx pattern and I think it highly related to gostar and the htmx pattern.

It has a HTTP / Web sockets API that can take JSONPATH and well as the JSON diff, merge, path pattern.   It's almost like a control plane for JSON.  SO we can use the Protojson to store the "graph"...   

Hope your following because its a bit of an abstraction. Hit me up on Telegram if you wanna shoot the shit on this one..

**Comment by gedw99** [comment]
> No, same as aframe, but not making the same engine choices they are

Yep I assumed that.
