### ISSUE TITLE
htmx patterns on backend and frontend

### ISSUE THREAD

**Issue by gedw99** [delaneyj/gostar#4]
I have been using htmx on both sides.

Just thought I would mention this.

It gives you best of both worlds, because you can do caching on the client.

**Comment by delaneyj** [comment]
I don't know what you mean by HTMX on the frontend... HTMX is about not having a separate frontend. What am I missing?

**Comment by gedw99** [comment]
I mean that it’s possible to compile for server , and to WASM for a browser with a Service worker.

the WASM version acts as a cache and calls the server if need be.

The db is corrosion which is a multi master crdt SQLite db.

https://github.com/superfly/corrosion

This all might be useful for others …

**Comment by delaneyj** [comment]
This seems to break the main draw of hypermedia, single place for state.  Not sure what problem this solves

**Comment by gedw99** [comment]
I agree that its breaks the state in one place, unless you using a synced state. 

Its more complex but you get SSR and SPA from the same golang code base.

you async load the WSM, while the SSR interactions are still running.

It's DEF not for everyone and much more complicated. But I needed Offline editing.

**Comment by gedw99** [comment]
Yeah it should be an issue in datastar - oops ..

will close this issue here and raise in datastar now
