### ISSUE TITLE
Reducing dependencies

### ISSUE THREAD

**Issue by paganotoni** [delaneyj/gostar#5]
Hello 👋 @delaneyj, I love this repo and the possibilities it opens (I bet you know this better 😅). One beneficial step the repo could take is to reduce the number of dependencies the library has.

I wonder if the generation task's dependencies end up in the repo. Would it be worth separating those two functions, e.g., into two separate modules? If that's a possibility, I would love to help. Thanks for this great package!

**Comment by delaneyj** [comment]
The are no runtime dependencies so not sure what problem you are trying to solve.  I have been concerns about dev deps but open to looking at specific changes.

**Comment by delaneyj** [comment]
I would like some help exploring a way to make multiple builds of datastar. For example one that goes into great lengths when it comes to errors and giving suggestions, but one that strips that all away for a more minimal size. I know there's ways to do this with the vite environment variables but I'm not sure how to set up to automatically handle multiple builds at the same time

**Comment by paganotoni** [comment]
@delaneyj thanks for the quick response! I'm not familiar with how [DataStar](https://github.com/delaneyj/datastar) is related to [Gostar](https://github.com/delaneyj/gostar). Just to make sure I'm being clear, I'm referring to the dependencies in [Gostar](https://github.com/delaneyj/gostar).

**Comment by delaneyj** [comment]
Oh, 😂 sorry about that. Sure, what are you thinking? Datastar (https://data-star.dev) is actually my major effort, gostar has built in support for it. Gostar is just my afternoon at fluent type safe gomponents

**Comment by paganotoni** [comment]
@delaneyj I'm thinking the code generation portion of the repo can be separated into a different module (hopefully the same repo). That way, when someone imports the gostar/elements module, only the modules required by the generated code are added as transitive dependencies of the app using the elements. Thoughts?

**Comment by paganotoni** [comment]
Also, it's nice to read some of the story behind all this! Thanks for sharing it.

**Comment by delaneyj** [comment]
For as a grok it, that's what happening now with tree shaking.  The elements get generated to happy to put anywhere

**Comment by paganotoni** [comment]
Oh, I see. So, is the idea of `gostar/elements` to be generated in the host app and used as a local import? I'm probably missing something here.

**Comment by delaneyj** [comment]
No, all the codegen goes into elements, and should get tree shook to just the parts you use.  First time compiling is slow but should barely effect user binary sizes after tree shook

**Comment by paganotoni** [comment]
I think you're right. I've started to use it and I see that it only imports the dependencies that the elements package has. Thanks for bearing with me.
