### ISSUE TITLE
How to (re)generate `cfg/spec_html.go`?

### ISSUE THREAD

**Issue by golightlyb** [delaneyj/gostar#9]
Hi, do you publish the code that generates `cfg/spec_html.go` from the spec?

(There's an ["old" generator](https://github.com/delaneyj/gostar/blob/main/generator/old/old_htmlspec.go), but I couldn't find an updated equivalent in the repo)

I made something similar a while ago for Python - [html5spec](https://github.com/tawesoft/html5spec) & [strictdom](https://github.com/tawesoft/strictdom) but I haven't touched it in 5 years & don't really want to. It's really good to see an up-to-date Go project doing a similar thing!

Thanks

**Comment by gedw99** [comment]
I also wanted to do this to add things for 3d models

**Comment by delaneyj** [comment]
The HTML Spec (same for SVG and MathML ) were generated by hand (with Copilot help) by literally going through the whole HTML spec by hand.  Covering every attribute and option.  

I tried multiple ways with DDL and specs gen but nothing was :100: 

It sucked to do, but now that it's done make codegen so much easier

**Comment by gedw99** [comment]
Good to know. Wow AI to the rescue.


so if the spec changes we have to manually fix it again ? I guess just diff the spec and manually fix the code gen code ?
